# Generated by Django 5.2 on 2025-10-22 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goals', '0002_alter_goalsmodel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('is_done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goals', models.ForeignKey(db_column='goals_id', on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='goals.goalsmodel')),
            ],
        ),
    ]
