# Generated by Django 5.2 on 2025-10-22 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalsmodel',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='accounts.user'),
        ),
    ]
